# Sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: wishlist-db-secret
  namespace: wishlist
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: java-client
  MYSQL_PASSWORD: password